[profile.default]
src            = "src"
test           = "test"
out            = "out"
libs           = ["lib"]
optimizer      = true
optimizer_runs = 200

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC}"

[profile.default.fuzz]
runs = 10000

[profile.default.invariant]
runs = 256
