// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// OpenZeppelin v5
// Install: npm install @openzeppelin/contracts
import "@openzeppelin/contracts/token/ERC721/extensions/ERC721URIStorage.sol";
import "@openzeppelin/contracts/access/AccessControl.sol";
import "@openzeppelin/contracts/utils/Pausable.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";

/**
 * @title EEPVengers
 * @notice Dynamic NFT (dNFT) contract for the 78 EEPVengers AI pet agents.
 * @dev ERC-721 with per-token URI storage. Metadata lives on IPFS and
 *      evolves as pets level up. The Python agent backend holds AGENT_ROLE
 *      and is the only caller of evolve().
 *
 * Architecture:
 *   - On-chain: ownership, evolution stage, IPFS CID pointer
 *   - Off-chain (Redis): hunger, energy, happiness, XP (high-frequency state)
 *   - IPFS: rendered metadata JSON + images (content-addressed, permanent)
 *
 * Author: welshDog (Lyndon Williams) — Hyperfocus Zone
 */
contract EEPVengers is ERC721URIStorage, AccessControl, Pausable, ReentrancyGuard {

    // ─── Roles ────────────────────────────────────────────────────────────────
    bytes32 public constant MINTER_ROLE = keccak256("MINTER_ROLE");
    bytes32 public constant AGENT_ROLE  = keccak256("AGENT_ROLE");   // Python backend only

    // ─── State ────────────────────────────────────────────────────────────────
    uint256 public constant MAX_SUPPLY      = 78;       // 78 EEPVengers. No more. Ever.
    uint256 public constant EVOLVE_COOLDOWN = 1 hours;  // Rate-limit agent calls

    uint256 private _nextTokenId = 1;

    /// @dev tokenId => evolution stage (1=Baby, 2=Young, 3=Trained, 4=Elite, 5=Legendary, 6=Quantum)
    mapping(uint256 => uint8)   public evolutionStage;

    /// @dev tokenId => off-chain pet_id string (e.g. "spider_001") for Python agent lookup
    mapping(uint256 => string)  public petId;

    /// @dev tokenId => timestamp of last evolve() call (cooldown enforcement)
    mapping(uint256 => uint256) public lastEvolved;

    // ─── Events ───────────────────────────────────────────────────────────────
    event PetMinted(uint256 indexed tokenId, address indexed owner, string petId, string ipfsCID);
    event PetEvolved(uint256 indexed tokenId, uint8 newStage, string newCID, uint256 timestamp);

    // ─── Constructor ──────────────────────────────────────────────────────────
    /**
     * @param adminMultisig  Gnosis Safe or EOA that holds DEFAULT_ADMIN_ROLE.
     *                       This is the only account that can grant/revoke roles.
     */
    constructor(address adminMultisig)
        ERC721("EEPVengers", "EEP")
    {
        _grantRole(DEFAULT_ADMIN_ROLE, adminMultisig);
        _grantRole(MINTER_ROLE,        adminMultisig);
    }

    // ─── Minting ──────────────────────────────────────────────────────────────
    /**
     * @notice Mint a new EEP to a recipient.
     * @param to        Recipient wallet address.
     * @param _petId    Off-chain identifier (e.g. "spider_001").
     * @param ipfsCID   IPFS CID of the initial (Baby stage) metadata JSON.
     */
    function mint(
        address to,
        string calldata _petId,
        string calldata ipfsCID
    )
        external
        onlyRole(MINTER_ROLE)
        whenNotPaused
        nonReentrant
    {
        require(_nextTokenId <= MAX_SUPPLY, "EEPVengers: All 78 EEPs minted");

        uint256 tokenId = _nextTokenId++;
        _safeMint(to, tokenId);
        _setTokenURI(tokenId, string(abi.encodePacked("ipfs://", ipfsCID)));

        evolutionStage[tokenId] = 1; // Baby
        petId[tokenId]          = _petId;

        emit PetMinted(tokenId, to, _petId, ipfsCID);
    }

    // ─── Evolution ────────────────────────────────────────────────────────────
    /**
     * @notice Update a pet's metadata CID when it evolves.
     * @dev Only callable by AGENT_ROLE (the Python FastAPI backend).
     *      Rate-limited by EVOLVE_COOLDOWN to protect against compromised agent keys.
     *
     * @param tokenId   The NFT token to evolve.
     * @param newCID    New IPFS CID of the updated metadata JSON (generated by metadata.py).
     * @param newStage  New evolution stage (1-6). Must be >= current stage.
     */
    function evolve(
        uint256 tokenId,
        string calldata newCID,
        uint8 newStage
    )
        external
        onlyRole(AGENT_ROLE)
        whenNotPaused
        nonReentrant
    {
        require(_ownerOf(tokenId) != address(0), "EEPVengers: Token does not exist");
        require(newStage >= evolutionStage[tokenId], "EEPVengers: Cannot de-evolve");
        require(newStage <= 6,                       "EEPVengers: Max stage is 6 (Quantum)");
        // lastEvolved == 0 means the pet has never evolved — first evolution is always allowed.
        require(
            lastEvolved[tokenId] == 0 || block.timestamp >= lastEvolved[tokenId] + EVOLVE_COOLDOWN,
            "EEPVengers: Evolution on cooldown"
        );

        _setTokenURI(tokenId, string(abi.encodePacked("ipfs://", newCID)));
        evolutionStage[tokenId] = newStage;
        lastEvolved[tokenId]    = block.timestamp;

        emit PetEvolved(tokenId, newStage, newCID, block.timestamp);
    }

    // ─── Views ────────────────────────────────────────────────────────────────

    /// @notice Total EEPs minted so far.
    function totalMinted() external view returns (uint256) {
        return _nextTokenId - 1;
    }

    /// @notice Seconds remaining until this token can evolve again. Returns 0 if ready.
    function evolveCooldownRemaining(uint256 tokenId) external view returns (uint256) {
        if (lastEvolved[tokenId] == 0) return 0; // Never evolved — ready immediately
        uint256 available = lastEvolved[tokenId] + EVOLVE_COOLDOWN;
        if (block.timestamp >= available) return 0;
        return available - block.timestamp;
    }

    // ─── Admin ────────────────────────────────────────────────────────────────

    /// @notice Emergency pause — freezes all mints and evolves.
    function pause()   external onlyRole(DEFAULT_ADMIN_ROLE) { _pause(); }

    /// @notice Unpause the contract.
    function unpause() external onlyRole(DEFAULT_ADMIN_ROLE) { _unpause(); }

    // ─── Overrides ────────────────────────────────────────────────────────────
    function supportsInterface(bytes4 interfaceId)
        public view override(ERC721URIStorage, AccessControl)
        returns (bool)
    {
        return super.supportsInterface(interfaceId);
    }
}
